export const FETCH_INITIAL = 'FETCH_INITIAL';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const ADD_INITIAL = 'ADD_INITIAL';
export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const ADD_FAILURE = 'ADD_FAILURE';

export const REMOVE_INITIAL = 'REMOVE_INITIAL';
export const REMOVE_REQUEST = 'REMOVE_REQUEST';
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';
export const REMOVE_FAILURE = 'REMOVE_FAILURE';

export const LESS_INITIAL = 'LESS_INITIAL';
export const LESS_REQUEST = 'LESS_REQUEST';
export const LESS_SUCCESS = 'LESS_SUCCESS';
export const LESS_FAILURE = 'LESS_FAILURE';

export const MODAL_INITIAL = 'MODAL_INITIAL';
export const MODAL_REQUEST = 'MODAL_REQUEST';
export const MODAL_SUCCESS = 'MODAL_SUCCESS';
export const MODAL_FAILURE = 'MODAL_FAILURE';

export const DELETE_INITIAL = 'DELETE_INITIAL';
export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';